export const fr = {
  shell: {
    brand: "Compass",
    home: "Accueil",
    method: "Méthode",
    learn: "Apprendre",
    kit: "Kit",
    navigation: "Navigation principale",
    footerNavigation: "Navigation du pied de page",
    sources: "Sources",
    sourceDate: "données au",
    reportIssue: "Signaler une erreur",
    footerStatement: "Lire le contexte d’une adresse commerciale parisienne à partir de données publiques.",
  },
  pages: {
    home: {
      eyebrow: "Compass · Paris",
      title: "Avant de signer un bail, lisez la rue.",
      searchLabel: "Quelle adresse regardez-vous ?",
      searchPlaceholder: "Rechercher une adresse",
      searchAction: "Rechercher",
      coveredAddresses: "Cette démo couvre quatre adresses",
      tradeLabel: "Quel commerce imaginez-vous ici ?",
      tradePlaceholder: "Votre métier",
      skipTrade: "Juste regarder",
      openAddress: "Lire cette adresse",
      recent: "Adresses récentes",
      recentKicker: "Reprendre une lecture",
      signalsKicker: "Autour de l’adresse de référence",
      signalsTitle: "Signaux publiés récemment",
      signalsIntro: "Cessions et procédures collectives publiées au BODACC dans un rayon de 400 m.",
      sale: "Cession",
      collective: "Procédure collective",
      map: "Carte des signaux BODACC autour du 82 place du Docteur Félix Lobligeois",
      registeredOffice: "Siège social : ce n’est pas nécessairement une boutique.",
      mapLegend: "signal BODACC localisé",
      openNotice: "Voir l’annonce",
    },
    method: { eyebrow: "Compass · Méthode", title: "Comment Compass lit-il un emplacement ?", text: "Les principes, les formules, les sources et leur fiabilité seront présentés ici." },
    learn: { eyebrow: "Compass · Apprendre", title: "Apprendre à lire une adresse commerciale", text: "Les guides, les questions fréquentes et le glossaire seront présentés ici." },
    context: { eyebrow: "Compass · Contexte", title: "Contexte de l’adresse", text: "La lecture complète de cette adresse sera présentée ici.", absent: "Adresse absente de cette démo" },
    visit: { eyebrow: "Compass · Phase 2", title: "Préparer la visite", text: "à venir" },
    visitPage: {
      eyebrow: "Compass · Visite",
      title: "Préparer la visite",
      lead: "La visite doit répondre à ce qu'aucune donnée publique ne dit ; Compass vous dit quoi regarder et quand venir.",
      dayTypes: "Type de jour",
      notYet: "pas encore dans Compass",
      notYetText: "Ce type de jour est chargé mais pas encore lu par Compass. Vacances, samedi et dimanche : à venir.",
      departures: "Départs uniquement — part de la journée de la station, jamais un volume, jamais comparable entre stations.",
      reading: "Une station compte les départs : matinale = quartier d'habitation, vespérale = bureaux ou destination.",
      station: "Station",
      counterTitle: "Compter soi-même",
      counterLead: "10 minutes, trois créneaux, relevé à votre nom. Ce compte est le vôtre : il reste dans ce navigateur et n'est pas une donnée Compass.",
      slot: "Créneau",
      start: "Démarrer 10 min",
      stop: "Arrêter",
      add: "+1 passant",
      reset: "Effacer",
      passersBy: "passants comptés",
      remaining: "restant",
      done: "Terminé",
    },
    dossier: {
      title: "Étude d’emplacement",
      issued: "Établie le",
      addressSource: "Adresse",
      print: "Imprimer le dossier",
      summary: "Synthèse",
      findings: "Constats documentés",
      history: "Histoire publiée de l’adresse",
      rhythm: "Rythme de la station proche",
      departures: "Départs — répartition de la journée",
      limits: "Limites connues",
      method: "Méthode et cadre",
      sale: "Cession",
      proceeding: "Procédure collective",
      survey: "Relevé de terrain",
      unavailable: "Information non fournie",
    },
    verify: { eyebrow: "Compass · Phase 3", title: "Vérifier un dossier", text: "à venir" },
  },
  confidence: {
    etabli: "Confiance : établi",
    corrobore: "Confiance : corroboré",
    probable: "Confiance : probable",
    indetermine: "Confiance : indéterminé",
  },
  retained: {
    label: "retenu — licence",
  },
  never: {
    label: "aucune donnée ouverte",
    action: "À faire à la place",
    actions: {
      "Loyer commercial": "Demandez le loyer, les charges et les conditions du bail au bailleur.",
      "Passage piéton": "Comptez vous-même les passants à plusieurs heures et plusieurs jours.",
    },
  },
  figure: {
    methods: {
      measured: "mesuré",
      derived: "dérivé",
      estimated: "estimé",
      modelled: "modélisé",
    },
    missing: "non mesuré",
  },
  method: {
    kicker: "Compass · Méthode",
    title: "Comment Compass lit-il un emplacement ?",
    intro: "Une méthode utile montre ses calculs, cite ses sources et nomme clairement ce qu’elle ignore.",
    navigation: "Sommaire de la méthode",
    sections: {
      principles: "Principes",
      formulas: "Formules",
      sources: "Sources",
      reliability: "Fiabilité",
      retained: "Ce qui est retenu, et pourquoi",
      progress: "Avancement",
    },
    leads: {
      principles: "Compass sépare les faits, les calculs et les limites pour laisser chaque commerce définir ses propres priorités.",
      formulas: "Chaque résultat calculé peut être vérifié depuis sa formule, ses constantes et les valeurs propres à l’adresse.",
      sources: "La fraîcheur d’une donnée dépend du calendrier de sa source, pas de la date à laquelle Compass la relit.",
      reliability: "La fiabilité décrit le lien entre une source et un local ; elle ne récompense jamais un résultat favorable.",
      retained: "Compass retient les calculs fondés sur 2017 et 2020 tant que la licence de ces relevés n’est pas lue.",
      progress: "Les prochaines étapes seront publiées ici lorsqu’elles pourront être décrites sans promesse spéculative.",
    },
    principleItems: [
      ["Pas de note unique", "Les axes restent séparés : une boulangerie, un café et un studio de yoga ne cherchent pas la même rue."],
      ["Une provenance visible", "Chaque fait servi nomme sa source, sa licence et sa date."],
      ["La méthode est qualifiée", "Mesuré, dérivé, estimé ou modélisé : le mode de production reste attaché au chiffre."],
      ["Le manque reste un manque", "Une valeur absente est dite non mesurée ; elle ne devient jamais zéro."],
      ["Une adresse n’est pas un local", "Le BODACC nomme une adresse, pas nécessairement la vitrine étudiée."],
    ],
    formula: "Formule",
    radius: "Rayon",
    constants: "Constantes",
    operands: "Exemple — valeurs de cette adresse",
    referenceAddress: "Exemple travaillé",
    sourceCadence: "Cadence",
    sourceAsOf: "Données au",
    confidenceDefinitions: {
      etabli: "La source nomme le local.",
      corrobore: "Deux sources concordent.",
      probable: "Le rattachement au local est déduit.",
      indetermine: "La source est muette.",
    },
    vintage: "Millésime",
    licence: "Licence",
    asOf: "Données au",
    progressValue: "à venir",
  },
  addressSheet: {
    kicker: "Compass · Contexte",
    sourceDateMissing: "date non fournie",
    shopfrontChoice: "Quelle vitrine regardez-vous ?",
    selectedShopfront: "Vitrine retenue dans cette démo",
    unavailableShopfront: "Le dossier détaillé de cette vitrine n’est pas présent dans cette démo.",
    chapters: {
      verdict: "Verdict",
      before: "Avant",
      today: "Aujourd’hui",
      tomorrow: "Demain",
      around: "Autour",
    },
    derivation: "D’où vient ce chiffre",
    calculation: "Calcul",
    radius: "Rayon",
    constants: "Constantes",
    operands: "Valeurs utilisées",
    timeline: "Histoire publiée de l’adresse",
    survey: "Relevé de terrain",
    sale: "Cession de fonds",
    proceeding: "Procédure collective",
    bodaccCaveat: "Le BODACC nomme une adresse, pas nécessairement ce local.",
    amount: "Prix publié",
    unit: "Le local relevé en 2023",
    unavailable: "non renseigné",
    yes: "oui",
    no: "non",
    activity: "Activité",
    family: "Famille",
    sign: "Enseigne",
    size: "Surface déclarée",
    situation: "Situation",
    terrace: "Terrasse autorisée",
    protected: "Linéaire commercial protégé",
    protectedCaveat: "Indication seulement : le Portail des règles d’urbanisme de la Ville fait foi.",
    station: "Station la plus proche",
    rhythm: "Le rythme de la journée",
    weekday: "Jour ouvré hors vacances",
    stationCaveat: "Une station n’est pas une rue",
    morning: "matin",
    midday: "midi",
    evening: "soir",
    rotation: "Rotation de la rue",
    signals: "Signaux publiés dans 400 m",
    sales: "Ventes",
    proceedings: "Procédures collectives",
    registeredOffice: "Siège social : ce n’est pas nécessairement une boutique.",
    sharedAddress: "Plusieurs locaux partagent cette adresse.",
    openNotice: "Voir l’annonce BODACC",
    noSignals: "Aucun signal dans cette famille.",
    limits: "Ce que les données ne disent pas",
    map: "Carte des locaux et signaux autour de l’adresse",
    mapPremises: "locaux relevés",
    mapUnit: "votre local",
    mapSignals: "signaux publiés",
    mapNoBasemap: "Fond cartographique non chargé · couches Compass réelles",
    source: "Source",
  },
} as const;