export const fr = {
  shell: {
    brand: "Compass",
    home: "Accueil",
    method: "Méthode",
    learn: "Apprendre",
    kit: "Kit",
    navigation: "Navigation principale",
    footerNavigation: "Navigation du pied de page",
    sources: "Sources",
    sourceDate: "données au",
    reportIssue: "Signaler une erreur",
    footerStatement: "Lire le contexte d’une adresse commerciale parisienne à partir de données publiques.",
  },
  pages: {
    home: { eyebrow: "Compass · Paris", title: "Avant de signer un bail, lisez la rue.", text: "L’accueil complet arrive dans la prochaine étape de cette démo." },
    method: { eyebrow: "Compass · Méthode", title: "Comment Compass lit-il un emplacement ?", text: "Les principes, les formules, les sources et leur fiabilité seront présentés ici." },
    learn: { eyebrow: "Compass · Apprendre", title: "Apprendre à lire une adresse commerciale", text: "Les guides, les questions fréquentes et le glossaire seront présentés ici." },
    context: { eyebrow: "Compass · Contexte", title: "Contexte de l’adresse", text: "La lecture complète de cette adresse sera présentée ici.", absent: "Adresse absente de cette démo" },
    visit: { eyebrow: "Compass · Phase 2", title: "Préparer la visite", text: "à venir" },
    dossier: { eyebrow: "Compass · Phase 2", title: "Dossier de l’adresse", text: "à venir" },
    verify: { eyebrow: "Compass · Phase 3", title: "Vérifier un dossier", text: "à venir" },
  },
  confidence: {
    etabli: "Confiance : établi",
    corrobore: "Confiance : corroboré",
    probable: "Confiance : probable",
    indetermine: "Confiance : indéterminé",
  },
  retained: {
    label: "retenu — licence",
  },
  never: {
    label: "aucune donnée ouverte",
    action: "À faire à la place",
    actions: {
      "Loyer commercial": "Demandez le loyer, les charges et les conditions du bail au bailleur.",
      "Passage piéton": "Comptez vous-même les passants à plusieurs heures et plusieurs jours.",
    },
  },
  figure: {
    methods: {
      measured: "mesuré",
      derived: "dérivé",
      estimated: "estimé",
      modelled: "modélisé",
    },
    missing: "non mesuré",
  },
  addressSheet: {
    kicker: "Compass · Contexte",
    sourceDateMissing: "date non fournie",
    shopfrontChoice: "Quelle vitrine regardez-vous ?",
    selectedShopfront: "Vitrine retenue dans cette démo",
    unavailableShopfront: "Le dossier détaillé de cette vitrine n’est pas présent dans cette démo.",
    chapters: {
      verdict: "Verdict",
      before: "Avant",
      today: "Aujourd’hui",
      tomorrow: "Demain",
      around: "Autour",
    },
    derivation: "D’où vient ce chiffre",
    calculation: "Calcul",
    radius: "Rayon",
    constants: "Constantes",
    operands: "Valeurs utilisées",
    timeline: "Histoire publiée de l’adresse",
    survey: "Relevé de terrain",
    sale: "Cession de fonds",
    proceeding: "Procédure collective",
    bodaccCaveat: "Le BODACC nomme une adresse, pas nécessairement ce local.",
    amount: "Prix publié",
    unit: "Le local relevé en 2023",
    unavailable: "non renseigné",
    yes: "oui",
    no: "non",
    activity: "Activité",
    family: "Famille",
    sign: "Enseigne",
    size: "Surface déclarée",
    situation: "Situation",
    terrace: "Terrasse autorisée",
    protected: "Linéaire commercial protégé",
    protectedCaveat: "Indication seulement : le Portail des règles d’urbanisme de la Ville fait foi.",
    station: "Station la plus proche",
    rhythm: "Le rythme de la journée",
    weekday: "Jour ouvré hors vacances",
    stationCaveat: "Une station n’est pas une rue",
    morning: "matin",
    midday: "midi",
    evening: "soir",
    rotation: "Rotation de la rue",
    signals: "Signaux publiés dans 400 m",
    sales: "Ventes",
    proceedings: "Procédures collectives",
    registeredOffice: "Siège social : ce n’est pas nécessairement une boutique.",
    sharedAddress: "Plusieurs locaux partagent cette adresse.",
    openNotice: "Voir l’annonce BODACC",
    noSignals: "Aucun signal dans cette famille.",
    limits: "Ce que les données ne disent pas",
    map: "Carte des locaux et signaux autour de l’adresse",
    mapPremises: "locaux relevés",
    mapUnit: "votre local",
    mapSignals: "signaux publiés",
    mapNoBasemap: "Fond cartographique non chargé · couches Compass réelles",
    source: "Source",
  },
} as const;